# Generated by Django 6.0.5 on 2026-05-23 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(unique=True)),
                ('winning_numbers', models.JSONField(blank=True, null=True)),
                ('bonus_number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_drawn', models.BooleanField(default=False)),
                ('drawn_at', models.DateTimeField(blank=True, null=True)),
                ('close_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.JSONField()),
                ('purchase_type', models.CharField(choices=[('AUTO', '자동'), ('MANUAL', '수동')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.draw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WinningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_count', models.PositiveIntegerField()),
                ('matched_bonus', models.BooleanField(default=False)),
                ('rank', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lotto.ticket')),
            ],
        ),
    ]
