# Generated by Django 5.2.14 on 2026-05-24 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winningresult',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winning_result', to='lotto.ticket'),
        ),
    ]
