# Generated by Django 5.2.14 on 2026-05-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='purchase_type',
            field=models.CharField(choices=[('AUTO', '자동'), ('MANUAL', '수동'), ('ML', 'ML 추천')], max_length=10),
        ),
    ]
